<?php

require_once dirname(__FILE__) . '/../../../../manager/includes/document.parser.class.inc.php';

/**
 * Test class for SystemEvent.
 * Generated by PHPUnit
 *
 * @author  Stefanie Janine Stoelting (mail@stefanie-stoelting.de)
 * @name    SystemEventTest
 * @package MODX
 * @subpackage unitTests
 * @license LGPL
 */
class SystemEventTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SystemEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SystemEvent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SystemEvent::alert
     * @todo Implement testAlert().
     */
    public function testAlert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SystemEvent::output
     * @todo Implement testOutput().
     */
    public function testOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SystemEvent::stopPropagation
     * @todo Implement testStopPropagation().
     */
    public function testStopPropagation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SystemEvent::_resetEventObject
     * @todo Implement test_resetEventObject().
     */
    public function test_resetEventObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

} // SystemEventTest
