<?php

require_once dirname(__FILE__) . '/../../../../manager/includes/document.parser.class.inc.php';

/**
 * Test class for SystemEvent.
 * Generated by PHPUnit
 *
 * @author  Stefanie Janine Stoelting (mail@stefanie-stoelting.de)
 * @name    SystemEventTest
 * @package MODX
 * @subpackage unitTests
 * @license LGPL
 */
class SystemEventTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SystemEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SystemEvent;
    } // setUp

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    } // tearDown

    /**
     * @covers SystemEvent::alert
     */
    public function testAlert() {
        $this->object = null;
        $this->object = new SystemEvent('TestEvent');
        $this->object->activePlugin = 'TestPlugin';
        
        $GLOBALS['SystemAlertMsgQueque'] = array();
        
        global $SystemAlertMsgQueque;


        $this->assertTrue(is_a($this->object, 'SystemEvent'));
        
        ($this->object->alert('Test message'));
        
        $this->assertTrue(is_array($SystemAlertMsgQueque));
        
        $this->assertContains('TestEvent', $SystemAlertMsgQueque[0]);
        $this->assertContains('TestPlugin', $SystemAlertMsgQueque[0]);
        $this->assertContains('Test message', $SystemAlertMsgQueque[0]);
    } // testAlert

    /**
     * @covers SystemEvent::output
     */
    public function testOutput() {
        $this->object->output('Test-1');      
        $this->assertEquals('Test-1', $this->object->_output);
        
        $this->object->output(';Test-2');        
        $this->assertEquals('Test-1;Test-2', $this->object->_output);
    } // testOutput

    /**
     * @covers SystemEvent::stopPropagation
     */
    public function testStopPropagation() {
        $this->assertTrue($this->object->_propagate);
        
        $this->object->stopPropagation();
        
        $this->assertFalse($this->object->_propagate);
    } // testStopPropagation

    /**
     * @covers SystemEvent::_resetEventObject
     */
    public function test_resetEventObject() {
        $this->object->stopPropagation();
        $this->object->output('Test-1');      
        
        $this->assertFalse($this->object->_propagate);
        $this->assertEquals('Test-1', $this->object->_output);
        
        $this->object->_resetEventObject();
        
        $this->assertTrue($this->object->_propagate);
        $this->assertEmpty($this->object->_output);
    } // test_resetEventObject

} // SystemEventTest
